seed: 1337

data:
  raw_root: ""
  processed_root: "data/processed_npy"
  channels: ["EEG Fpz-Cz"]
  fs: 100
  epoch_sec: 30
  zscore: true
  train_frac: 0.6
  val_frac: 0.2

train:
  batch_size: 160
  lr: 1.0e-3
  weight_decay: 1.0e-4
  epochs: 80
  warmup_epochs: 5
  early_stop_patience: 30
  grad_accum: 1
  loss: ce
  gamma: 0.0
  label_smoothing: 0.05
  balanced_sampler: true
  class_weighted_loss: false
  prior_bias_init: true
  augment:
    enabled: false

eval:
  batch_size: 256

model:
  name: tcn
  in_channels: 1
  num_classes: 5
  base_channels: 16
  dropout: 0.1
  context_len: 15
  tcn_channels: 128
  tcn_layers: 6

tta:
  mode: tent
  entropy_gate: 1.2
  ema_decay: 0.99
  max_steps_per_window: 2
  lr: 5.0e-5
  steps: 1
  weight_decay: 0.0
  bn_momentum: 0.01
